apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config # Name used to reference this ConfigMap
  namespace: default # Or the namespace where you deploy the backend
data:
  # IMPORTANT: Replace with your actual comma-separated allowed origins
  # Example: "http://localhost:3000,https://your-prod-app.vercel.app,https://your-preview-app.vercel.app"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,https://www.synoptica.dev/,https://syn-data-gen.vercel.app/" 

  # IMPORTANT: Replace with your actual Google Cloud Project ID
  GCP_PROJECT_ID: "valid-song-450602-m7" 