"use client";
import React from "react";
import { motion } from "motion/react";
import { WavyBackground } from "@/components/ui/wavy-background";
import { SparklesCore } from "@/components/ui/sparkles";
import { Button as MagicButton } from "@/components/ui/bmagic-button";
import Link from "next/link";
import { FeaturesGrid } from '@/components/landing/features-grid';
import WaitlistSection from "@/components/waitlist-section";
import { Footer } from "@/components/landing/footer";
import { LogosWithBlurFlip } from "@/components/landing/logos-with-blur-flip";

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen bg-white dark:bg-black">
      <WavyBackground id="top" className="flex-grow flex flex-col items-center justify-center pb-40">
         <h1 className="md:text-7xl text-4xl lg:text-8xl font-bold text-center text-white relative z-8 mb-4">
           Synoptic
         </h1>

         <div className="w-full md:w-[40rem] h-0 relative">
            <div className="absolute inset-x-20 top-0 bg-gradient-to-r from-transparent via-indigo-500 to-transparent h-[2px] w-3/4 blur-sm" />
            <div className="absolute inset-x-20 top-0 bg-gradient-to-r from-transparent via-indigo-500 to-transparent h-px w-3/4" />
            <div className="absolute inset-x-60 top-0 bg-gradient-to-r from-transparent via-sky-500 to-transparent h-[5px] w-1/4 blur-sm" />
            <div className="absolute inset-x-60 top-0 bg-gradient-to-r from-transparent via-sky-500 to-transparent h-px w-1/4" />
         </div>

         <p className="text-neutral-600 dark:text-neutral-300 max-w-xl mx-auto my-6 text-center text-lg relative z-10">
           Power your AI models, test applications, and ensure privacy with realistic, scalable synthetic data generated by Synoptic.
         </p>
         <div className="flex flex-col sm:flex-row items-center gap-4 mt-6 relative z-10">
           <Link href="#waitlist">
             <MagicButton>
                Request A Demo
             </MagicButton>
           </Link>
         </div>
      </WavyBackground>
      <div id="partners" className="-mt-8 mb-32 scroll-mt-10">
        <LogosWithBlurFlip />
      </div>
      <div id="features" className="mb-20 scroll-mt-55">
        <FeaturesGrid />
      </div>
      <div id="waitlist" className="mb-32 scroll-mt-20">
        <WaitlistSection />
      </div>
      <Footer />
    </div>
  );
}
